/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Exercise {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'muscleGroup' : MuscleGroup,
}
export interface ExerciseSet {
  'setNumber' : bigint,
  'weight' : number,
  'exerciseId' : bigint,
  'reps' : bigint,
}
export type FitnessGoal = { 'generalFitness' : null } |
  { 'fatLoss' : null } |
  { 'muscleGain' : null } |
  { 'endurance' : null };
export type MuscleGroup = { 'shoulders' : null } |
  { 'arms' : null } |
  { 'back' : null } |
  { 'core' : null } |
  { 'chest' : null } |
  { 'legs' : null } |
  { 'cardio' : null };
export interface Profile {
  'age' : bigint,
  'weight' : number,
  'height' : number,
  'goal' : FitnessGoal,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkoutEntry { 'date' : string, 'sessionId' : bigint }
export interface WorkoutPlan {
  'difficulty' : { 'intermediate' : null } |
    { 'beginner' : null } |
    { 'advanced' : null },
  'schedule' : Array<[string, Array<Exercise>]>,
}
export interface WorkoutSession {
  'id' : bigint,
  'sets' : Array<ExerciseSet>,
  'user' : Principal,
  'notes' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addWorkoutEntry' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createWorkoutSession' : ActorMethod<[string, Array<ExerciseSet>], bigint>,
  'getAllWorkoutPlans' : ActorMethod<[], Array<WorkoutPlan>>,
  'getAllWorkoutSessions' : ActorMethod<[Principal], Array<WorkoutSession>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExerciseById' : ActorMethod<[bigint], Exercise>,
  'getExerciseProgress' : ActorMethod<
    [Principal, bigint],
    Array<[string, bigint, number]>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getWeightHistory' : ActorMethod<[Principal], Array<[string, number]>>,
  'getWorkoutHistory' : ActorMethod<[Principal], Array<WorkoutEntry>>,
  'getWorkoutPlanByName' : ActorMethod<[string], WorkoutPlan>,
  'getWorkoutSession' : ActorMethod<[bigint], WorkoutSession>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllExercises' : ActorMethod<[], Array<Exercise>>,
  'logWeight' : ActorMethod<[string, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];