/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExerciseSet = IDL.Record({
  'setNumber' : IDL.Nat,
  'weight' : IDL.Float64,
  'exerciseId' : IDL.Nat,
  'reps' : IDL.Nat,
});
export const MuscleGroup = IDL.Variant({
  'shoulders' : IDL.Null,
  'arms' : IDL.Null,
  'back' : IDL.Null,
  'core' : IDL.Null,
  'chest' : IDL.Null,
  'legs' : IDL.Null,
  'cardio' : IDL.Null,
});
export const Exercise = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'muscleGroup' : MuscleGroup,
});
export const WorkoutPlan = IDL.Record({
  'difficulty' : IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  }),
  'schedule' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Exercise))),
});
export const WorkoutSession = IDL.Record({
  'id' : IDL.Nat,
  'sets' : IDL.Vec(ExerciseSet),
  'user' : IDL.Principal,
  'notes' : IDL.Text,
});
export const FitnessGoal = IDL.Variant({
  'generalFitness' : IDL.Null,
  'fatLoss' : IDL.Null,
  'muscleGain' : IDL.Null,
  'endurance' : IDL.Null,
});
export const Profile = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Float64,
  'height' : IDL.Float64,
  'goal' : FitnessGoal,
  'name' : IDL.Text,
});
export const WorkoutEntry = IDL.Record({
  'date' : IDL.Text,
  'sessionId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addWorkoutEntry' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createWorkoutSession' : IDL.Func(
      [IDL.Text, IDL.Vec(ExerciseSet)],
      [IDL.Nat],
      [],
    ),
  'getAllWorkoutPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
  'getAllWorkoutSessions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WorkoutSession)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExerciseById' : IDL.Func([IDL.Nat], [Exercise], ['query']),
  'getExerciseProgress' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Float64))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getWeightHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getWorkoutHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WorkoutEntry)],
      ['query'],
    ),
  'getWorkoutPlanByName' : IDL.Func([IDL.Text], [WorkoutPlan], ['query']),
  'getWorkoutSession' : IDL.Func([IDL.Nat], [WorkoutSession], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'logWeight' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExerciseSet = IDL.Record({
    'setNumber' : IDL.Nat,
    'weight' : IDL.Float64,
    'exerciseId' : IDL.Nat,
    'reps' : IDL.Nat,
  });
  const MuscleGroup = IDL.Variant({
    'shoulders' : IDL.Null,
    'arms' : IDL.Null,
    'back' : IDL.Null,
    'core' : IDL.Null,
    'chest' : IDL.Null,
    'legs' : IDL.Null,
    'cardio' : IDL.Null,
  });
  const Exercise = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'muscleGroup' : MuscleGroup,
  });
  const WorkoutPlan = IDL.Record({
    'difficulty' : IDL.Variant({
      'intermediate' : IDL.Null,
      'beginner' : IDL.Null,
      'advanced' : IDL.Null,
    }),
    'schedule' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Exercise))),
  });
  const WorkoutSession = IDL.Record({
    'id' : IDL.Nat,
    'sets' : IDL.Vec(ExerciseSet),
    'user' : IDL.Principal,
    'notes' : IDL.Text,
  });
  const FitnessGoal = IDL.Variant({
    'generalFitness' : IDL.Null,
    'fatLoss' : IDL.Null,
    'muscleGain' : IDL.Null,
    'endurance' : IDL.Null,
  });
  const Profile = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Float64,
    'height' : IDL.Float64,
    'goal' : FitnessGoal,
    'name' : IDL.Text,
  });
  const WorkoutEntry = IDL.Record({ 'date' : IDL.Text, 'sessionId' : IDL.Nat });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addWorkoutEntry' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createWorkoutSession' : IDL.Func(
        [IDL.Text, IDL.Vec(ExerciseSet)],
        [IDL.Nat],
        [],
      ),
    'getAllWorkoutPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
    'getAllWorkoutSessions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WorkoutSession)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExerciseById' : IDL.Func([IDL.Nat], [Exercise], ['query']),
    'getExerciseProgress' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Float64))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getWeightHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getWorkoutHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WorkoutEntry)],
        ['query'],
      ),
    'getWorkoutPlanByName' : IDL.Func([IDL.Text], [WorkoutPlan], ['query']),
    'getWorkoutSession' : IDL.Func([IDL.Nat], [WorkoutSession], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'logWeight' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };