/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    id: bigint;
    name: string;
    description: string;
    muscleGroup: MuscleGroup;
}
export interface WorkoutPlan {
    difficulty: Variant_intermediate_beginner_advanced;
    schedule: Array<[string, Array<Exercise>]>;
}
export interface WorkoutSession {
    id: bigint;
    sets: Array<ExerciseSet>;
    user: Principal;
    notes: string;
}
export interface Profile {
    age: bigint;
    weight: number;
    height: number;
    goal: FitnessGoal;
    name: string;
}
export interface WorkoutEntry {
    date: string;
    sessionId: bigint;
}
export interface ExerciseSet {
    setNumber: bigint;
    weight: number;
    exerciseId: bigint;
    reps: bigint;
}
export enum FitnessGoal {
    generalFitness = "generalFitness",
    fatLoss = "fatLoss",
    muscleGain = "muscleGain",
    endurance = "endurance"
}
export enum MuscleGroup {
    shoulders = "shoulders",
    arms = "arms",
    back = "back",
    core = "core",
    chest = "chest",
    legs = "legs",
    cardio = "cardio"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_intermediate_beginner_advanced {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addWorkoutEntry(sessionId: bigint, date: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createWorkoutSession(notes: string, sets: Array<ExerciseSet>): Promise<bigint>;
    getAllWorkoutPlans(): Promise<Array<WorkoutPlan>>;
    getAllWorkoutSessions(user: Principal): Promise<Array<WorkoutSession>>;
    getCallerUserProfile(): Promise<Profile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExerciseById(id: bigint): Promise<Exercise>;
    getExerciseProgress(user: Principal, exerciseId: bigint): Promise<Array<[string, bigint, number]>>;
    getUserProfile(user: Principal): Promise<Profile | null>;
    getWeightHistory(user: Principal): Promise<Array<[string, number]>>;
    getWorkoutHistory(user: Principal): Promise<Array<WorkoutEntry>>;
    getWorkoutPlanByName(name: string): Promise<WorkoutPlan>;
    getWorkoutSession(sessionId: bigint): Promise<WorkoutSession>;
    isCallerAdmin(): Promise<boolean>;
    listAllExercises(): Promise<Array<Exercise>>;
    logWeight(date: string, weight: number): Promise<void>;
    saveCallerUserProfile(profile: Profile): Promise<void>;
}
import type { Exercise as _Exercise, FitnessGoal as _FitnessGoal, MuscleGroup as _MuscleGroup, Profile as _Profile, UserRole as _UserRole, WorkoutPlan as _WorkoutPlan } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addWorkoutEntry(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkoutEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkoutEntry(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createWorkoutSession(arg0: string, arg1: Array<ExerciseSet>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkoutSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkoutSession(arg0, arg1);
            return result;
        }
    }
    async getAllWorkoutPlans(): Promise<Array<WorkoutPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkoutPlans();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkoutPlans();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWorkoutSessions(arg0: Principal): Promise<Array<WorkoutSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkoutSessions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkoutSessions(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExerciseById(arg0: bigint): Promise<Exercise> {
        if (this.processError) {
            try {
                const result = await this.actor.getExerciseById(arg0);
                return from_candid_Exercise_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExerciseById(arg0);
            return from_candid_Exercise_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExerciseProgress(arg0: Principal, arg1: bigint): Promise<Array<[string, bigint, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExerciseProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExerciseProgress(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeightHistory(arg0: Principal): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeightHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeightHistory(arg0);
            return result;
        }
    }
    async getWorkoutHistory(arg0: Principal): Promise<Array<WorkoutEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutHistory(arg0);
            return result;
        }
    }
    async getWorkoutPlanByName(arg0: string): Promise<WorkoutPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutPlanByName(arg0);
                return from_candid_WorkoutPlan_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutPlanByName(arg0);
            return from_candid_WorkoutPlan_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutSession(arg0: bigint): Promise<WorkoutSession> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutSession(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllExercises();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllExercises();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async logWeight(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWeight(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWeight(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_Profile_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_Profile_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Exercise_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Exercise {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_FitnessGoal_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FitnessGoal): FitnessGoal {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_MuscleGroup_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MuscleGroup): MuscleGroup {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutPlan_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutPlan): WorkoutPlan {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    muscleGroup: _MuscleGroup;
}): {
    id: bigint;
    name: string;
    description: string;
    muscleGroup: MuscleGroup;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        muscleGroup: from_candid_MuscleGroup_n12(_uploadFile, _downloadFile, value.muscleGroup)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    weight: number;
    height: number;
    goal: _FitnessGoal;
    name: string;
}): {
    age: bigint;
    weight: number;
    height: number;
    goal: FitnessGoal;
    name: string;
} {
    return {
        age: value.age,
        weight: value.weight,
        height: value.height,
        goal: from_candid_FitnessGoal_n17(_uploadFile, _downloadFile, value.goal),
        name: value.name
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    difficulty: {
        intermediate: null;
    } | {
        beginner: null;
    } | {
        advanced: null;
    };
    schedule: Array<[string, Array<_Exercise>]>;
}): {
    difficulty: Variant_intermediate_beginner_advanced;
    schedule: Array<[string, Array<Exercise>]>;
} {
    return {
        difficulty: from_candid_variant_n6(_uploadFile, _downloadFile, value.difficulty),
        schedule: from_candid_vec_n7(_uploadFile, _downloadFile, value.schedule)
    };
}
function from_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, Array<_Exercise>]): [string, Array<Exercise>] {
    return [
        value[0],
        from_candid_vec_n9(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shoulders: null;
} | {
    arms: null;
} | {
    back: null;
} | {
    core: null;
} | {
    chest: null;
} | {
    legs: null;
} | {
    cardio: null;
}): MuscleGroup {
    return "shoulders" in value ? MuscleGroup.shoulders : "arms" in value ? MuscleGroup.arms : "back" in value ? MuscleGroup.back : "core" in value ? MuscleGroup.core : "chest" in value ? MuscleGroup.chest : "legs" in value ? MuscleGroup.legs : "cardio" in value ? MuscleGroup.cardio : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    generalFitness: null;
} | {
    fatLoss: null;
} | {
    muscleGain: null;
} | {
    endurance: null;
}): FitnessGoal {
    return "generalFitness" in value ? FitnessGoal.generalFitness : "fatLoss" in value ? FitnessGoal.fatLoss : "muscleGain" in value ? FitnessGoal.muscleGain : "endurance" in value ? FitnessGoal.endurance : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): Variant_intermediate_beginner_advanced {
    return "intermediate" in value ? Variant_intermediate_beginner_advanced.intermediate : "beginner" in value ? Variant_intermediate_beginner_advanced.beginner : "advanced" in value ? Variant_intermediate_beginner_advanced.advanced : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutPlan>): Array<WorkoutPlan> {
    return value.map((x)=>from_candid_WorkoutPlan_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, Array<_Exercise>]>): Array<[string, Array<Exercise>]> {
    return value.map((x)=>from_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Array<Exercise> {
    return value.map((x)=>from_candid_Exercise_n10(_uploadFile, _downloadFile, x));
}
function to_candid_FitnessGoal_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessGoal): _FitnessGoal {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Profile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profile): _Profile {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    weight: number;
    height: number;
    goal: FitnessGoal;
    name: string;
}): {
    age: bigint;
    weight: number;
    height: number;
    goal: _FitnessGoal;
    name: string;
} {
    return {
        age: value.age,
        weight: value.weight,
        height: value.height,
        goal: to_candid_FitnessGoal_n23(_uploadFile, _downloadFile, value.goal),
        name: value.name
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessGoal): {
    generalFitness: null;
} | {
    fatLoss: null;
} | {
    muscleGain: null;
} | {
    endurance: null;
} {
    return value == FitnessGoal.generalFitness ? {
        generalFitness: null
    } : value == FitnessGoal.fatLoss ? {
        fatLoss: null
    } : value == FitnessGoal.muscleGain ? {
        muscleGain: null
    } : value == FitnessGoal.endurance ? {
        endurance: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
